{% set name = "eiger-io" %}
{% set name_ = name.replace('-', '_') %}
{% set version = "2.01" %}
{% set sha256 = "7431e36b45da5d8c777561066dee9badfcede48b8d5e257c115cbd6db040b3ff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - h5py
    - hdf5-lz4
    - numpy
    - pims
    - six

test:
  imports:
    - {{ name_ }}

about:
  home: https://github.com/NSLS-II/eiger-io
  license: BSD  # TODO: add a license file in the repo and feedstock
  summary: I/O tools for the Eiger detector
