{% set name = "eiger-io" %}
{% set name_ = name.replace('-', '_') %}
{% set version = "2.0.4" %}
{% set sha256 = "40f79e360c300a71dd358f5881c3e361ce08a0ce2780e953e0531bef27c65ad6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NSLS-II/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - h5py
    - hdf5-external-filter-plugins-bitshuffle
    - hdf5-external-filter-plugins-lz4
    - numpy
    - pims
    - six

test:
  imports:
    - {{ name_ }}

about:
  home: https://github.com/NSLS-II/eiger-io
  license: BSD  # TODO: add a license file in the repo and feedstock
  license_file: LICENSE
  summary: I/O tools for the Eiger detector
